const tools=[
 ['list_models','List configured routing targets, tiers and declared capabilities',{type:'object',properties:{}}],
 ['provider_inventory','Inventory all registered providers without exposing secrets',{type:'object',properties:{}}],
 ['discover_models','Discover models from provider /models endpoints',{type:'object',properties:{provider:{type:'string'},refresh:{type:'boolean'}}}],
 ['health_check','Probe configured providers/models in parallel',{type:'object',properties:{}}],
 ['project_init','Create/update canonical shared project memory',{type:'object',required:['project_id'],properties:{project_id:{type:'string'},workspace:{type:'string'},repository:{type:'string'},branch:{type:'string'}}}],
 ['mission_status','Read shared mission state and recent journal events',{type:'object',required:['project_id','mission_id'],properties:{project_id:{type:'string'},mission_id:{type:'string'}}}],
 ['memory_checkpoint','Persist a handoff checkpoint for another harness/agent',{type:'object',required:['project_id','mission_id'],properties:{project_id:{type:'string'},mission_id:{type:'string'},next_action:{type:'string'},status:{type:'string'}}}],
 ['delegate','Delegate one task with automatic provider failover and context continuity',{type:'object',required:['prompt'],properties:{project_id:{type:'string'},mission_id:{type:'string'},goal:{type:'string'},prompt:{type:'string'},role:{type:'string'},target:{type:'string'}}}],
 ['consensus','Ask multiple independent models/reviewers',{type:'object',required:['prompt'],properties:{project_id:{type:'string'},mission_id:{type:'string'},prompt:{type:'string'},models:{type:'integer',minimum:2,maximum:5}}}],
 ['swarm_run','Run parallel specialist subagents; multiple workers may share a provider',{type:'object',required:['goal'],properties:{project_id:{type:'string'},mission_id:{type:'string'},goal:{type:'string'},roles:{type:'array',items:{type:'string'}},max_agents:{type:'integer',minimum:1,maximum:32}}}]
].map(([name,description,inputSchema])=>({name,description,inputSchema}));
function result(v){return {content:[{type:'text',text:JSON.stringify(v,null,2)}],structuredContent:v};}
export function createMcpHandler(router,memory){return async msg=>{if(msg.method==='initialize')return {protocolVersion:'2025-06-18',capabilities:{tools:{listChanged:false}},serverInfo:{name:'dz23-subagents-universal',version:'2.2.4'}};if(msg.method?.startsWith('notifications/'))return null;if(msg.method==='ping')return {};if(msg.method==='tools/list')return {tools};if(msg.method==='tools/call'){const a=msg.params?.arguments||{};switch(msg.params?.name){case'list_models':return result(router.listModels());case'provider_inventory':return result(router.inventory());case'discover_models':return result(await router.discover(a));case'health_check':return result(await router.healthCheck());case'project_init':return result(await memory.initProject(a.project_id,{workspace:a.workspace||'',repository:a.repository||'',branch:a.branch||''}));case'mission_status':return result({state:await memory.getMission(a.project_id,a.mission_id),recent_events:await memory.recentEvents(a.project_id,a.mission_id,40)});case'memory_checkpoint':return result(await memory.checkpoint(a.project_id,a.mission_id,{next_action:a.next_action||'',status:a.status||'active'}));case'delegate':return result(await router.delegate(a));case'consensus':return result(await router.consensus(a));case'swarm_run':return result(await router.swarmRun(a));default:throw new Error(`Unknown tool: ${msg.params?.name}`);}}throw new Error(`Unsupported MCP method: ${msg.method}`);};}
export function toolDefinitions(){return tools;}
